name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Pode ser 'zulu', 'corretto', etc., dependendo da necessidade
          java-version: '23'
          cache: maven

      - name: Construir o projeto com Maven
        run: mvn clean install -B
